name: Run Unit Test Suites

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go Environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.21.4'
      - name: Run Unit Test Suites
        working-directory: ./
        run: |
          make test
